name: PointsAPI
version: 1.6.7
author: GiantTree
main: net.groundmc.pointsapi.PointsAPIPlugin

commands:
  pa:
    description: PointsAPI
    permission: pointsapi.admin
    usage: /<command> <get|add|remove|set> <name|uuid> [amount]

permissions:
  pointsapi.admin:
    description: Grants administrative access to this plugin
    default: op
